# --- CONFIGURACIÓN GLOBAL ---
add_newline = true

# El orden: info a la izquierda -> relleno -> reloj -> salto de línea -> cursor
format = """
$sudo\
$directory\
$git_branch\
$git_status\
$nodejs\
$cmd_duration\
$memory_usage\
$fill\
$time\
$line_break\
$character"""

# --- MÓDULOS ---

[directory]
style = "bold cyan"
truncation_length = 3
truncation_symbol = "…/"
format = "[$path]($style)[$read_only]($read_only_style) "

[fill]
symbol = "─"
style = "#333333" 

[git_branch]
symbol = "🌱 "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "🏳 "
ahead = "🏎💨 "
behind = "🐢 "
diverged = "🔱 "
untracked = "🤷 "
stashed = "📦 "
modified = "📝 "
staged = "✅ "
renamed = "🚚 "
deleted = "🗑 "

[nodejs]
symbol = " "
style = "bold green"
format = "via [$symbol($version)]($style) "

[cmd_duration]
min_time = 500
style = "bold yellow"
format = "tardó [$duration]($style) "

[memory_usage]
symbol = "󰍛 "
threshold = 90 
style = "bold red"
format = "usando [$symbol$ram_pct]($style) "

[time]
disabled = false
time_format = "%R" 
style = "bold #555555" 
format = " [$time]($style)" 

[line_break]
disabled = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[sudo]
symbol = "🔒 "
style = "bold red"
disabled = false